linters:
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: tab
    width: 1

  ColorVariable:
    enabled: false

  SingleLinePerSelector:
    enabled: false

  PropertySortOrder:
    enabled: false

  TrailingWhitespace:
    enabled: false

  VendorPrefix:
    enabled: false
